TARBALL=EWKZ2Jets_ZToLL_M-50_13TeV-madgraph-pythia8_tarball.tar.xz
HADRONIZER=EWKZ2Jets_ZToLL_M-50_13TeV-madgraph-pythia8_hadronizer.py
PROCESS=EWKZ2Jets_ZToLL_M-50_13TeV-madgraph-pythia8
USERNAME=bmaier
